### PR TITLE
Use v1 Tekton API

### PR DESCRIPTION
**Pull request by zregvart**
ref: EC-29

### CODE REVIEW

**Comment by simonbaird** [comment]
I thought these were updated automatically through some CI, possibly https://github.com/enterprise-contract/tekton-catalog/actions/workflows/sync-ec-cli-tasks.yaml but now that I look at it, perhaps it is just going to bump the digests.

**Review by simonbaird — APPROVED** [review]

**Comment by zregvart** [comment]
Yeah, that was my thought initially, we only update the digests. (Mental note, if we change the Task definitions we need to update here as well)

**Comment by lcarva** [comment]
Hmm.. it should be copying everything over: https://github.com/enterprise-contract/tekton-catalog/blob/16133b7a7bddf5a8effa4480ab7108c6a9eb4dcd/hack/sync-ec-cli-tasks.sh#L29

Basically, no manual changes should be done against the task directory. At least that was the intention. Maybe something is broken?

**Comment by zregvart** [comment]
Most likely I looked at it too quickly and failed to see what is done...

**Pull request merged**
